message entry {
  0: string key
  1: int value
}

service kvs {
  #@cht(1) #@update #@pass
  bool put(0: string key, 1: int value)

  #@cht(1) #@analysis #@pass
  entry get(0: string key)

  #@random #@analysis #@pass
  float get_average()
}
