service kvs {
  #@cht(2) #@update #@all_and
  bool put(0: string key, 1: string value)

  #@cht(2) #@analysis #@pass
  string get(0: string key)

  #@cht(2) #@update #@all_and
  bool del(0: string key)

  #@broadcast #@update #@all_and
  bool clear()
}
