// this program is automatically generated by jenerator. do not edit.
#include <jubatus/framework.hpp>
#include <jubatus/framework/aggregators.hpp>
#include <jubatus/common/exception.hpp>
#include "kvs_types.hpp"
#include <glog/logging.h>
using namespace jubatus;
using namespace jubatus::framework;
int main(int args, char** argv){
  try{
    keeper k(keeper_argv(args,argv,"kvs"));
    k.register_async_cht<2, bool, std::string >("put", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
    k.register_async_cht<2, std::string >("get", pfi::lang::function<std::string(std::string,std::string)>(&pass<std::string >)); //analysis
    k.register_async_cht<2, bool >("del", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
    k.register_async_broadcast<bool >("clear", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
    k.register_async_broadcast<std::map<std::string,std::map<std::string,std::string > > >("get_status", pfi::lang::function<std::map<std::string,std::map<std::string,std::string > >(std::map<std::string,std::map<std::string,std::string > >,std::map<std::string,std::map<std::string,std::string > >)>(&merge<std::string,std::map<std::string,std::string > >)); //analysis
    k.register_async_broadcast<bool, std::string >("save", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
    k.register_async_broadcast<bool, std::string >("load", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
    return k.run();
  } catch (const jubatus::exception::jubatus_exception& e) {
    LOG(FATAL) << e.diagnostic_information(true);
    return -1;
  }
}
